eBooks_MVC/Controllers/AutoriController.cs
using eBooks_MVC.Models;
using LibrarieModele;

using NivelAccessDate;

using NivelServicii;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace eBooks_MVC.Controllers
{
    public class AutoriController : Controller
    {
        private readonly IAutorService autorService;

        // GET: Autori
        public ActionResult Index()
        {
            var autori = autorService.GetAll();
            var model = autori.Select(a => new AutorViewModel
            {
                id_autor = a.id_autor,
                nume_autor = a.nume_autor,
                data_nasterii = a.data_nasterii,
                tara_origine = a.tara_origine,
                activ = true
            }).ToList();

            return View(model);
        }

        // GET: Autori/Details
        public ActionResult Details(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);

            var autor = autorService.GetById(id.Value);
            if (autor == null)
                return HttpNotFound();

            var model = new AutorViewModel
            {
                id_autor = autor.id_autor,
                nume_autor = autor.nume_autor,
                data_nasterii = autor.data_nasterii,
                tara_origine = autor.tara_origine,
                activ = true
            };

            return View(model);
        }
        // ==============================
        // CREATE
        // ==============================

        // GET: Autori/Create
        public ActionResult Create()
        {
            return View(new AutorViewModel());
        }

        // POST: Autori/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(AutorViewModel model)
        {
            if (ModelState.IsValid)
            {
                var autor = new LibrarieModele.Autor
                {
                    nume_autor = model.nume_autor,
                    data_nasterii = model.data_nasterii,
                    tara_origine = model.tara_origine
                };

                autorService.Add(autor);
                return RedirectToAction("Index");
            }

            return View(model);
        }

        // ==============================
        // EDIT
        // ==============================

        // GET: Autori/Edit
        public ActionResult Edit(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);

            var autor = autorService.GetById(id.Value);
            if (autor == null)
                return HttpNotFound();

            var model = new AutorViewModel
            {
                id_autor = autor.id_autor,
                nume_autor = autor.nume_autor,
                data_nasterii = autor.data_nasterii,
                tara_origine = autor.tara_origine
            };

            return View(model);
        }

        // POST: Autori/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(AutorViewModel model)
        {
            if (ModelState.IsValid)
            {
                var autor = new LibrarieModele.Autor
                {
                    id_autor = model.id_autor,
                    nume_autor = model.nume_autor,
                    data_nasterii = model.data_nasterii,
                    tara_origine = model.tara_origine
                };

                autorService.Update(autor);
                return RedirectToAction("Index");
            }

            return View(model);
        }

        // GET: Autori/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var autor = autorService.GetById(id.Value);
            if (autor == null)
                return HttpNotFound();

            var model = new AutorViewModel
            {
                id_autor = autor.id_autor,
                nume_autor = autor.nume_autor,
                data_nasterii = autor.data_nasterii,
                tara_origine = autor.tara_origine
            };

            return View(model);
        }

        // POST: Autori/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            autorService.Delete(id); 
            return RedirectToAction("Index");
        }


    }
}

eBooks_MVC/Views/Autori/Create.cshtml
@model eBooks_MVC.Models.AutorViewModel


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Detalii Autor</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <!-- Nume autor -->
        <div class="form-group">
            @Html.LabelFor(model => model.nume_autor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nume_autor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nume_autor, "", new { @class = "text-danger" })
            </div>
        </div>

        <!-- Data nasterii -->
        <div class="form-group">
            @Html.LabelFor(model => model.data_nasterii, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.data_nasterii, new { htmlAttributes = new { @class = "form-control", type = "date" } })
                @Html.ValidationMessageFor(model => model.data_nasterii, "", new { @class = "text-danger" })
            </div>
        </div>

        <!-- Tara origine -->
        <div class="form-group">
            @Html.LabelFor(model => model.tara_origine, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tara_origine, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tara_origine, "", new { @class = "text-danger" })
            </div>
        </div>

        <!-- Activ -->
        <div class="form-group">
            @Html.LabelFor(model => model.activ, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10 checkbox">
                @Html.CheckBoxFor(model => model.activ)
                @Html.ValidationMessageFor(model => model.activ, "", new { @class = "text-danger" })
            </div>
        </div>

        <!-- Buton creare -->
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvează" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Înapoi la listă", "Index", null, new { @class = "btn btn-secondary" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

eBooks_MVC/Views/Autori/Delete.cshtml
@model eBooks_MVC.Models.AutorViewModel

<h2>Confirmare ștergere</h2>

<p>Vrei să marchezi autorul <strong>@Model.nume_autor</strong> ca inactiv?</p>

@using (Html.BeginForm("Delete", "Autori", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.id_autor)
    <button type="submit" class="btn btn-warning">Ștergere logică</button>
    @Html.ActionLink("Renunță", "Index", null, new { @class = "btn btn-secondary" })
}

eBooks_MVC/Views/Autori/Details.cshtml
@model eBooks_MVC.Models.AutorViewModel

@{
    ViewBag.Title = "Detalii autor";
}

<h2>@ViewBag.Title</h2>

<div>
    <h4>@Model.nume_autor</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>Țara</dt>
        <dd>@Model.tara_origine</dd>

        <dt>Data nașterii</dt>
        <dd>@Model.data_nasterii.ToShortDateString()</dd>

        <dt>Activ</dt>
        <dd>@Html.CheckBoxFor(m => m.activ, new { disabled = "disabled" })</dd>
    </dl>
</div>

<p>
    @Html.ActionLink("Înapoi la listă", "Index")
</p>

eBooks_MVC/Views/Autori/Edit.cshtml
@model eBooks_MVC.Models.AutorViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>AutorViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.id_autor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.id_autor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.id_autor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nume_autor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nume_autor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nume_autor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.data_nasterii, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.data_nasterii, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.data_nasterii, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tara_origine, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tara_origine, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tara_origine, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.activ, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.activ)
                    @Html.ValidationMessageFor(model => model.activ, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

eBooks_MVC/Views/Autori/Index.cshtml
@model IEnumerable<eBooks_MVC.Models.AutorViewModel>

<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>Nume autor</th>
            <th>Țara</th>
            <th>Data nașterii</th>
            <th>Acțiuni</th> 
        </tr>
    </thead>
    <tbody>
        @foreach (var autor in Model)
        {
            <tr>
                <td>@autor.nume_autor</td>
                <td>@autor.tara_origine</td>
                <td>@autor.data_nasterii.ToShortDateString()</td>
                <td>
                    @Html.ActionLink("Detalii", "Details", new { id = autor.id_autor }, new { @class = "btn btn-info btn-sm" })
                    @Html.Raw(" ")
                    @Html.ActionLink("Editează", "Edit", new { id = autor.id_autor }, new { @class = "btn btn-warning btn-sm" })
                    @Html.Raw(" ")
                    @Html.ActionLink("Șterge", "Delete", new { id = autor.id_autor }, new { @class = "btn btn-danger btn-sm" })
                </td>
            </tr>
        }
    </tbody>
</table>