eBooks_MVC/Controllers/CartiController.cs
using eBooks_MVC.Models;

using LibrarieModele;

using NivelAccessDate;

using Repository_CodeFirst;

using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace eBooks_MVC.Controllers
{
    public class CartiController : Controller
    {

        private readonly eBooksContext context = new eBooksContext();
        private readonly CarteAccessor carteAccessor = new CarteAccessor();

        // GET: Carti
        public ActionResult Index()
        {
            var carti = context.Carti.Include("Autor").ToList();
            var model = carti.Select(c => new CarteViewModel
            {
                id_carte = c.id_carte,
                titlu = c.titlu,
                descriere = c.descriere,
                id_autor = c.id_autor,
                nume_autor = c.Autor != null ? c.Autor.nume_autor : "N/A"
            }).ToList();

            return View(model);
        }


        // ==============================
        // CREATE
        // ==============================

        // GET: Carti/Create
        public ActionResult Create()
        {
            return View(new CarteViewModel(context));
        }


        //POST: Carti/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CarteViewModel model)
        {
            if (ModelState.IsValid)
            {
                var carte = new Carte
                {
                    titlu = model.titlu,
                    descriere = model.descriere,
                    id_autor = model.id_autor
                };

                context.Carti.Add(carte);
                context.SaveChanges();
                return RedirectToAction("Index");
            }

            model.Autori = context.Autori
                .Select(a => new SelectListItem
                {
                    Text = a.nume_autor,
                    Value = a.id_autor.ToString()
                }).ToList();

            return View(model);
        }


        // GET:Autori/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var carte = carteAccessor.GetById(id.Value);
            if (carte == null)
                return HttpNotFound();

            var model = new CarteViewModel
            {
                id_carte = carte.id_carte,
                titlu = carte.titlu,
                descriere = carte.descriere
            };

            return View(model);
        }
        // POST: Autori/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            carteAccessor.Delete(id); // aici poate fi logic sau fizic
            return RedirectToAction("Index");
        }
    }
    
}

eBooks_MVC/Views/Carti/Create.cshtml
@model eBooks_MVC.Models.CarteViewModel



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Detalii Carte</h4>
    <hr />
    
    <div class="form-group">
        @Html.LabelFor(m => m.titlu, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(m => m.titlu)
            @Html.ValidationMessageFor(m => m.titlu)
        </div>
    </div>
    
    <div class="form-group">
        @Html.LabelFor(m => m.descriere, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(m => m.descriere)
            @Html.ValidationMessageFor(m => m.descriere)
        </div>
    </div>

   
    <div class="form-group">
        @Html.LabelFor(m => m.id_autor, "Autor", new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(m => m.id_autor, Model.Autori, "Selectează autorul", new { @class = "form-control" }
            )
            @Html.ValidationMessageFor(m => m.id_autor)
        </div>
    </div>

   
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Salvează" class="btn btn-success" />
        </div>
    </div>
</div>
}

eBooks_MVC/Views/Carti/Delete.cshtml
@model eBooks_MVC.Models.CarteViewModel

<h2>Confirmare ștergere</h2>

<p>Ești sigur că vrei să ștergi cartea: <strong>@Model.titlu</strong>?</p>

@using (Html.BeginForm("Delete", "Carti", FormMethod.Post))
{
    @Html.HiddenFor(m => m.id_carte)
    <button type="submit" class="btn btn-danger">Șterge</button>
    @Html.ActionLink("Renunță", "Index", null, new { @class = "btn btn-secondary" })
}

eBooks_MVC/Views/Carti/Index.cshtml
@model IEnumerable<eBooks_MVC.Models.CarteViewModel>

<h2>Lista Cărți</h2>

<p>
    @Html.ActionLink("Adaugă carte nouă", "Create", null, new { @class = "btn btn-primary" })
</p>

<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>Titlu</th>
            <th>Descriere</th>
            <th>Autor</th>
            <th>Acțiuni</th> 
        </tr>
    </thead>
    <tbody>
        @foreach (var carte in Model)
        {
            <tr>
                <td>@carte.titlu</td>
                <td>@carte.descriere</td>
                <td>@carte.nume_autor</td>
               
            </tr>
        }
    </tbody>
</table>