eBooks_MVC/Controllers/AutoriApiController.cs
using eBooks_MVC.Models.Api;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Net.Http;
using System.Net.Http.Formatting;


namespace eBooks_MVC.Controllers
{
    public class AutoriApiController : Controller
    {
        private readonly HttpClient client = new HttpClient
        {
            BaseAddress = new Uri("http://proiect-api-demo.com/api/")
        };

        public async Task<ActionResult> Index()
        {
            var response = await client.GetAsync("autori");
            if (!response.IsSuccessStatusCode) return View(new List<AutorApiModel>());
            var autori = await response.Content.ReadAsAsync<List<AutorApiModel>>();
            return View(autori);
        }

        public ActionResult Create() => View();

        [HttpPost]
        public async Task<ActionResult> Create(AutorApiModel model)
        {
            if (!ModelState.IsValid) return View(model);
            var response = await client.PostAsJsonAsync("autori", model);
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> Edit(int id)
        {
            var response = await client.GetAsync($"autori/{id}");
            var autor = await response.Content.ReadAsAsync<AutorApiModel>();
            return View(autor);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(AutorApiModel model)
        {
            var response = await client.PutAsJsonAsync($"autori/{model.id_autor}", model);
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> Delete(int id)
        {
            var response = await client.GetAsync($"autori/{id}");
            var autor = await response.Content.ReadAsAsync<AutorApiModel>();
            return View(autor);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            await client.DeleteAsync($"autori/{id}");
            return RedirectToAction("Index");
        }
    }


}

eBooks_MVC/Views/AutoriApi/Create.cshtml
@model eBooks_MVC.Models.Api.AutorApiModel

@{
    ViewBag.Title = "Adauga autor";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />

        <div class="form-group">
            @Html.LabelFor(m => m.nume_autor, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.nume_autor, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.nume_autor)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.tara_origine, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.tara_origine, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.tara_origine)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.data_nasterii, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.data_nasterii, new { @class = "form-control", placeholder = "yyyy-MM-dd" })
          
                @Html.ValidationMessageFor(m => m.data_nasterii)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvează" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Înapoi la listă", "Index")
</div>

eBooks_MVC/Views/AutoriApi/Delete.cshtml
@model eBooks_MVC.Models.Api.AutorApiModel

@{
    ViewBag.Title = "Șterge autor";
}

<h2>Confirmă ștergerea</h2>

<div>
    <h4>@Model.nume_autor</h4>
    <p>Țara: @Model.tara_origine</p>
    <p>Data nașterii: @Model.data_nasterii</p>
</div>

@using (Html.BeginForm("DeleteConfirmed", "AutoriApi", new { id = Model.id_autor }, FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <p>Sigur vrei să ștergi acest autor?</p>

    <input type="submit" value="Da, șterge" class="btn btn-danger" />
    @Html.ActionLink("Anulează", "Index", null, new { @class = "btn btn-default" })
}

eBooks_MVC/Views/AutoriApi/Edit.cshtml
@model eBooks_MVC.Models.Api.AutorApiModel

@{
    ViewBag.Title = "Editează autor";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.id_autor)

    <div class="form-horizontal">
        <hr />

        <div class="form-group">
            @Html.LabelFor(m => m.nume_autor, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.nume_autor, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.nume_autor)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.tara_origine, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.tara_origine, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.tara_origine)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.data_nasterii, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.data_nasterii, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.data_nasterii)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvează" class="btn btn-warning" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Înapoi la listă", "Index")
</div>

eBooks_MVC/Views/AutoriApi/Index.cshtml
@model IEnumerable<eBooks_MVC.Models.Api.AutorApiModel>

@{
    ViewBag.Title = "Lista autorilor (API)";
}

<h2>@ViewBag.Title</h2>

<p>
    @Html.ActionLink("Adaugă autor nou", "Create", null, new { @class = "btn btn-primary" })
</p>

<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>Nume autor</th>
            <th>Țara</th>
            <th>Data nașterii</th>
            <th>Acțiuni</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var autor in Model)
        {
            <tr>
                <td>@autor.nume_autor</td>
                <td>@autor.tara_origine</td>
                <td>@autor.data_nasterii</td>

                <td>
                    @Html.ActionLink("Editează", "Edit", new { id = autor.id_autor }, new { @class = "btn btn-warning btn-sm" })
                    @Html.Raw(" ")
                    @Html.ActionLink("Șterge", "Delete", new { id = autor.id_autor }, new { @class = "btn btn-danger btn-sm" })
                </td>
            </tr>
        }
    </tbody>
</table>